### ISSUE TITLE
The gem5-resources submodule does not contain a commit "d0201312a88788f572d62ab25a7960e900d3dd4d"

### ISSUE THREAD

**Issue by BobbyRBruce** [darchr/gem5-resources-launch#1]
We have a gem5-resources submodule in the root of our project that points towards some revision "d0201312a88788f572d62ab25a7960e900d3dd4d". This doesn't appear to exist. I get the following error when running `git submodule update --init --recursive`:

```
Submodule 'gem5-resources' (https://gem5.googlesource.com/public/gem5-resources) registered for path 'gem5-resources'
Cloning into '/home/bobbyrbruce/Desktop/bruce2021enabling-artifact/gem5-resources-launch/gem5-resources'...
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'gem5-resources', but it did not contain d0201312a88788f572d62ab25a7960e900d3dd4d. Direct fetching of that commit failed.
```

Side-note: The README doesn't mention getting this submodule (it it necessary?). It probably should.

**Comment by hnpl** [comment]
The submodule problem is fixed by,
-  https://github.com/darchr/gem5-resources-launch/commit/fcb72d53d0e9089ccd5d796d3c20b80fc4fe007b
-  https://github.com/darchr/gem5-resources-launch/commit/28e8caa5016775ce51e2c9d4ba5a961483136830.

The README file has been updated to note about recursively cloning the repo here,
-  https://github.com/darchr/gem5-resources-launch/commit/d8f94c156b9996787e4b519038b1ec5e3d6e5d5d
